### ISSUE TITLE
Dashboard: Subtier icons (eg Office/grounds) don't have benchmark graphs (see below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#210]
![capture](https://user-images.githubusercontent.com/26979575/36125870-bdf877f0-100a-11e8-99c9-b62fa0e11e8e.PNG)

**Comment by smirolo** [comment]
Both the icon and "system" link are called Office/grounds. The icon tag was tagged for use in the scorecard instead of the "system" link below it. As a result the default chart is set to `null` on the Office/grounds page.

Fixed by switching the scorecard tag around.

Note that the Office/grounds > Office/grounds construct is a workaround issues describe in #58.
