### ISSUE TITLE
Links from emails not working

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#94]
I am getting a "403 - Permission Denied" error. Strange, because I was able to access the website via links from when sent from a different profile. In case this is an error to do with my email or system, I added you as all three type of users so that you can check the links out.

**Comment by smirolo** [comment]
A viewer that tried to access the scorecard for an organization before any self-assessment was started would end-up on the /benchmark page and thus get a 403 permission denied. /app redirects to /scorecard and forced back to /benchmark for manager and contributor now.

**Comment by deborabonner** [comment]
**WHAT IS HAPPENING:** Links are definitely not working. From the "erin" profile, I invited a new user, Jon, that had never registered in the system. I got the note saying "this is a chance to add a new user etc". I sent the invite. Jon received it. He clicked on the links in the email and was taken to "Reset password" page. He then clicked the "sign in" button at top right of screen and navigated from the "sign in" screen to the "Sign up" page. The system wouldn't let him register, because it said "A user with that email already exists".  

**WHAT SHOULD HAPPEN:** New invited users should be able to view a scorecard without signing up. They should have access to nothing other than the scorecard they are invited to view.

**Comment by smirolo** [comment]
Showing the set password page is normal behavior as it is the first time Jon connects to the site (need to activate account). Maybe we should remove all other links from the page so that Jon does not wonder off.

If we allow invited users to view a scorecard without authenticating, this means the scorecard is available publicly to everyone on the Internet. The only way to mitigate this publicly-visible feature is then to use a very cryptic URL that cannot be easily guessed or brute forced.

1. Should we enforce private/authenticated access to scorecard?, or
2. Implement a publicly-visible scorecards using cryptic URLs?

**Comment by deborabonner** [comment]
First one, but make the pathway less confusing by changing "Reset password" to "Set password" or to "Set/Reset password"?

**Comment by deborabonner** [comment]
Should have added to prior email "and remove links to "Sign up" page.

**Comment by deborabonner** [comment]
I tried the process with another colleague today (ccwg@pge.com). She received the you've-been-added-as-Viewer email, clicked the links, was taken to "Reset password" page  (which is going to be changed as mentioned in comment above). When she clicked the Submit button she got the screen shown below. 
![capture2](https://user-images.githubusercontent.com/26979575/29341473-63c8013e-81d9-11e7-98b6-f827aca43e95.PNG)
